#pragma config(Sensor, in1,    blahY,          sensorAccelerometer)
#pragma config(Sensor, in2,    blahX,          sensorAccelerometer)
#pragma config(Motor,  port2,           Right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Left,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	writeDebugStreamLine("bias = %d (%d) %d (%d)", SensorBias[blahX], SensorScale[blahX], SensorBias[blahY], SensorScale[blahY]);
	while(true) {
		// Left:  V:Ch3 H:Ch4
	  // Right: V:Ch2 H:Ch1

	  motor[Right] = vexRT[Ch2];
		motor[Left]  = vexRT[Ch3];

		bool cheater = vexRT[Btn5U] && vexRT[Btn6D];

		int shock =
		  abs(SensorValue[blahX]) +
		  abs(SensorValue[blahY]);
		//writeDebugStreamLine("shock=%d", shock);
		// Driver goes to the Penalty box if the accelerometer triggers
		if (shock > 1000 && !cheater) {
			motor[Left] = 0;
			motor[Right] = 0;
			sleep(10000);  // 10s
			clearLCDLine(1);
		}
	}
}
